---
- name: Remove Larbs voidrice repo
  file:
    name: ~/.git
    state: absent

- name: Create temp dir for git
  tempfile:
    state: directory
  register: temp_git

- name: Add my voidrice fork
  git:
    repo: https://github.com/Kabix1/voidrice
    dest: "{{ temp_git.path }}"

- name: Copy voidrice configs to home folder
  synchronize:
    src: "{{ temp_git.path }}/"
    dest: /home/vagrant/
  delegate_to: "{{ inventory_hostname }}"
